[book]
title = "Localargo Documentation"
authors = ["William Born"]
description = "Documentation for Localargo, a Python CLI tool"
language = "en"

[build]
build-dir = "book"
create-missing = false

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
smart-punctuation = true
mathjax-support = false
copy-fonts = true
additional-css = []
additional-js = []
no-section-label = false
git-repository-url = "https://github.com/William Born/localargo"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/William Born/localargo/edit/main/docs/{path}"
site-url = "/localargo/"
